# Generated by Django 4.0.3 on 2022-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='uploads/banner-img/')),
                ('banner_name', models.CharField(max_length=100, null=True)),
                ('banner_taglines', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
